### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by willemvb** [spatie/viewport-utility#1]
- [ ] jumpTo (like scrollTo, without animation)
- [ ] scrollTo callback, speed
- [ ] inView watcher: set classes on elements in view (with accompanied nav for onepagers?)
